### ISSUE TITLE
Feature request - save template

### ISSUE THREAD

**Issue by sajiby3k** [cmason3/jinjafx#25]
Hi,

Thanks for developing jinja2fx.

I wan to make a feature request.

Jinja2fx already has support for saving data portion of a template.

Can you please implement s save function so that it saves both the template and it's related data.

Without template the data is useless.

A save function that saves both jinja template and yml data.

Regards

**Comment by cmason3** [comment]
I assume you are referring to the web front end at https://jinjafx.io - there is currently an option to "Export" which outputs a DataTemplate in YAML format (details at https://github.com/cmason3/jinjafx#jinjafx-datatemplates) which contains "data.csv", "vars.yml" as well as "template.j2". You also have the option to save a copy on the server by clicking on the "Get Link" button - this saves all elements in a DataTemplate format.

The command line jinjafx.py also supports the ability to read this DataTemplate format using `-dt`.
