### ISSUE TITLE
Feature Request: Ability to save j2 template with dataset

### ISSUE THREAD

**Issue by netopsengineer** [cmason3/jinjafx#48]
Hello,

Fantastic library @cmason3 !  I have been looking for something that could minimally keep the datasets, but ideally, I would love to be able to attach a dataset to a specific template, so that I can recall the whole package to regenerate the output.  The use case would be regeneration of repeat markup, readme's, ansible role documentation, collection documentation, argument specs, it would be awesome to make a change and regenerate all of the templates from the dataset.  Paired with something like MkDocs, you could have a nice documentation setup "as code" or relatively close to it :)

**Comment by cmason3** [comment]
Thanks, is this specific to the command line tool and being able to have a single file with the template and data instead of having separate files? 

In the GUI at https://jinjafx.io there is the ability to click on “Export” which combines the data with the template, which can be pasted back in. I used to include support for passing that format on the command line but recently removed it.

**Comment by netopsengineer** [comment]
@cmason3 

Thanks for the reply!  I honestly see it as a bit of both, where online I could have a drop down that selected a stored template and its associated datasets, where I could author and test with them, or let others do the same.  Ultimately, we would then use them more programmatically via the CLI to output the contents in the target directory the generated content belongs in.

A use case that comes to mine is an Ansible Galaxy Collection, it has readme files all over the place, roles, modules, etc, any time you need to update them, risk of missing one, so I would like to look at the documentation as ephemeral artifacts I can regenerate when modifications are required.  Almost a template source of truth in a sense.

 Honestly, I have thought of so many ways I could use this to reduce alot of manual swivel chair that I do when authoring alot of markup in general.  A team could have a scaffold template that created consistent scripts, configurations, etc that you could pre-store, and would allow them to explore your dataset on the web with the template, so they know what your variable naming schema looks like, etc.   This tool really has so many potential use cases because its both a web app, and CLI, I've not found anything like it.

**Comment by cmason3** [comment]
Check out `v1.11.0` as I have added support to specify a DataTemplate (`-dt`) which combines Data, Vars and a Template into a single YAML file [(https://github.com/cmason3/jinjafx#jinjafx-datatemplates)](https://github.com/cmason3/jinjafx#jinjafx-datatemplates). It also includes DataSets (`-ds`) which allows you to include multiple Data and Vars with a common Template in a single DataTemplate file.

**Comment by netopsengineer** [comment]
Awesome! I will give it a shot this weekend, and shoot you some feedback.
