### ISSUE TITLE
Add netutils filters

### ISSUE THREAD

**Issue by ryanmerolle** [cmason3/jinjafx#59]
Add netutils filters:

https://netutils.readthedocs.io/en/latest/netutils/utilities/index.html#netutils-to-jinja2-filters

**Comment by cmason3** [comment]
I will have a look - are there any filters of particular interest as we have a bit of duplication with what netutils provides and what is already provided via other sources (e.g. [ipaddr](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html))? We also already support Cisco Type 7 encoding, Type 8 hashing, Type 9 hashing, Juniper Type 6 hashing and Type 9 encoding.

**Comment by ryanmerolle** [comment]
The interface and bandwidth filters.

**Comment by cmason3** [comment]
There is a security challenge in adding 3rd party filters to JinjaFx without porting the actual filters - anything which is enabled by default in JinjaFx is enabled in the Web UI (https://jinjafx.io) - a filter could then be added to NetUtils code which could be used for file system operations.

While I think about this, the easiest way to use NetUtils filters would be to create a small extension as follows:

**~/.jinjafx/ext-netutils.py**
```
from jinja2.ext import Extension
from netutils.utils import jinja2_convenience_function

class NetUtils(Extension):
  def __init__(self, environment):
    Extension.__init__(self, environment)
    environment.filters.update(jinja2_convenience_function())
```

You can then reference this extension using the following:

**vars.yml**
```
jinja2_extensions:
  - 'ext-netutils.NetUtils'
```

You are then able to use any of the NetUtils filters in your template.
